openapi: 3.0.1
info:
  title: Web-shop API
  description: >
    This is a REpresentational State Transfer (REST) API that is basically a CRUD interface.  <br>
    These APIs are the absolutely most simple types you can come across, where we basically use a API only for data storage. <br>
    However, it is important to remember that REST != CRUD
  version: 1.0.0
paths:
  /products:
    get:
      summary: Retrieve all products in the shop
      responses:
        200:
          description: List of every product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /cart:
    get:
      summary: Retrieve the cart
      responses:
        200:
          description: Cart response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    post:
      summary: Create a new cart
      responses:
        201:
          description: Cart successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /cart/{cartId}/items:
    post:
      summary: Add item(s) to the cart
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
        - in: query
          name: item
          description: Product to add to the cart
          required: true
          schema:
            type: object
            properties:
              productId:
                type: string
                description: ID of the product
              quantity:
                type: integer
                description: Quantity of products
                minimum: 1
      responses:
        200:
          description: Item(s) added to cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    put:
      summary: Empty the cart
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  description: Empties the cart by replacing the list with an empty one
                  items:
                    type: string
      responses:
        204:
          description: SUCCESS, cart emptied
  /cart/{cartId}/items/{itemId}:
    put:
      summary: Update the cart
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
        - in: path
          name: itemId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Updates quantity of the product in the cart (0 removes every product with that id)
                  minimum: 0
      responses:
        204:
          description: Cart updated successfully
components:
  schemas:
    Product:
      type: object
      description: Representation of a Product Resource
      properties:
        id:
          type: string
        name:
          type: string
        productType:
          type: string
        productInformation:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
              releaseYear:
                type: integer
        price:
          type: number
        imageUrl:
          type: string
          format: uri
    Cart:
      type: object
      description: Representation of a Cart Resource
      properties: 
        cartId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
